WIP: Auto create time layers in geoserver_publisher
meggsimum/sauber-sdi-docker pull request #61
Opened 2021-02-19 13:53 UTC by chrismayer

This creates time enabled WMS layers for the given ImageMosaic stores if not already existing in the GeoServer.

2021-06-18 09:39 UTC, JakobMiksch approved these changes
The code looks fine. Some minor remarks.

2021-06-18 09:39 UTC, JakobMiksch commented on geoserver_publisher/index.js
> + * @param {Object} rasterMetaInf
A description of the input would be helpful

2021-06-18 09:39 UTC, JakobMiksch commented on geoserver_publisher/index.js
> +  const srs = 'EPSG:3035'; //TODO check if defined in DB
whitespace

```suggestion
  const srs = 'EPSG:3035'; // TODO check if defined in DB
```

2021-06-18 09:39 UTC, JakobMiksch commented on geoserver_publisher/index.js
> +    verboseLogging(`Time dimension  for layer "${ws}:${layerName}" successfully enabled?`, timeEnabled);
superfluous whitespace
```suggestion
    verboseLogging(`Time dimension for layer "${ws}:${layerName}" successfully enabled?`, timeEnabled);
```

2021-06-18 09:39 UTC, JakobMiksch commented on geoserver_publisher/index.js
> +    // publishDbRaster (workspace, coverageStore, nativeName, name, title, srs, enabled)
maybe a quick comment that this should describe the input of the function below. 
On first sight, I thought this was a commented functionCall

2021-06-18 10:28 UTC, JakobMiksch requested changes
I need to test it locally before I can approve finally

2021-06-23 08:29 UTC, JakobMiksch approved these changes
I finally tested it locally on my machine. The functions seem to be called, but since i do not have rasters they also cannot be published. @chrismayer please merge at will

2021-06-23 09:12 UTC, chrismayer commented
Thanks for the review. I'd like to wait what @jdk24 says to this.

2021-06-23 16:08 UTC, jdk24 requested changes
The [image mosaic template ](https://github.com/meggsimum/sauber-sdi-docker/blob/master/geoserver_publisher/gs-img-mosaic-tpl/datastore.properties#L7) which is read [here](https://github.com/meggsimum/sauber-sdi-docker/pull/61/files#diff-ca92621faca806ac3b80fe78d54e869f91ea735480602d00a3e730e33cddc7ebR92) still contains the early-days standard DB password. 

On attempting to create a new image mosaic, this results in `failed to create reader from file` from GeoServer so far. 

Geoserver_publisher probably needs to have access to the relevant secret and insert it into the template.

2021-06-24 06:53 UTC, JakobMiksch commented
@jdk24 @chrismayer I will approach this issue of adding the secret

2021-06-25 12:14 UTC, chrismayer commented
> Geoserver_publisher probably needs to have access to the relevant secret and insert it into the template.

Implemented and rebased the original commit. Please have another look.

2021-06-30 09:28 UTC, chrismayer commented
> https://github.com/meggsimum/sauber-sdi-docker/blob/b95624dabe80be55b120733f42741f979b69b6c2/docker-stack.yml#L302-L305
> 
> Please add
> 
> ```
>  - sauber_manager_password
> ```

Nice catch @jdk24 :gun: I addressed this and also the remarks of @JakobMiksch. 

> ## **Edit:**
> Updating `docker-stack.yml` does allow the raster publisher to create an ImgMosaic store & publish a time-enabled raster layer from incoming raster data. The bbox and time dimension are set correctly.
> 
> On trying to query the layer however, I get [this error](https://github.com/meggsimum/sauber-sdi-docker/files/6732112/wms-6.txt). This also happens when
> 
> 1. manually creating a layer in the automatically created ImgMosaic store
> 2. manually creating a ImgMosaic store & layer
> 3. manually publishing the incoming raster as simple GTIFF layer
> 
> all after cleaning geoserver_mnt, deleting stack volumes, restarting, etc. The files exist on the server and the PostGIS index looks sound.

So since this seems to be unrelated to this PR because it also appears when manually creating an ImageMosaic store & layer (as described in 2.) I vote for merging this, if you are OK. The error described above should be documented in a separate Issue and be handled in a separate PR.

2021-06-30 13:03 UTC, jdk24 approved these changes
LGTM. ImgStore created, Layer published and time dimension enabled. Please merge at will!

2021-06-30 13:07 UTC, chrismayer commented
Thanks for your reviews! I'll merge now.

2021-06-30 13:08 UTC, merged